import { expect, test } from '@playwright/test'

for (const width of [375, 1440]) {
  test(`drawer opens from the right and restores focus at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 812 })
    await page.goto('/')
    const opener = page.getByRole('button', { name: 'Меню', exact: true })
    await opener.click()
    const drawer = page.getByRole('dialog', { name: 'Навигация' })
    const close = drawer.getByRole('button', { name: 'Закрыть меню' })
    await expect(drawer).toBeVisible()
    await expect(drawer).toHaveCSS('transform', 'matrix(1, 0, 0, 1, 0, 0)')
    const box = await drawer.boundingBox()
    expect(box!.y).toBe(0)
    expect(box!.x + box!.width).toBeCloseTo(width, 0)
    expect(box!.width).toBeLessThanOrEqual(512)
    await expect(close).toBeFocused()
    await expect(page.locator('body')).toHaveCSS('overflow', 'hidden')
    await page.screenshot({ path: `test-results/qa-drawer-${width}.png`, animations: 'disabled' })
    await page.keyboard.press('Shift+Tab')
    await expect(drawer.getByRole('link', { name: 'В подарок' })).toBeFocused()
    await page.keyboard.press('Tab')
    await expect(close).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(drawer).not.toBeVisible()
    await expect(opener).toBeFocused()
    await expect(page.locator('body')).not.toHaveCSS('overflow', 'hidden')
  })
}

test('drawer backdrop closes the panel without navigating', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Меню', exact: true }).click()
  const drawer = page.getByRole('dialog', { name: 'Навигация' })
  await expect(drawer).toHaveCSS('transform', 'matrix(1, 0, 0, 1, 0, 0)')
  await page.mouse.click(100, 300)
  await expect(drawer).not.toBeVisible()
  await expect(page).toHaveURL(/\/$/)
})

test('drawer stays usable in landscape and with enlarged text', async ({ page }) => {
  await page.setViewportSize({ width: 812, height: 375 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Меню', exact: true }).click()
  const drawer = page.getByRole('dialog', { name: 'Навигация' })
  await expect(drawer).toHaveCSS('transform', 'matrix(1, 0, 0, 1, 0, 0)')
  await drawer.getByRole('link', { name: 'В подарок' }).scrollIntoViewIfNeeded()
  await expect(drawer.getByRole('link', { name: 'В подарок' })).toBeInViewport()
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 375, height: 812 })
  await page.evaluate(() => { document.documentElement.style.fontSize = '200%' })
  await page.getByRole('button', { name: 'Меню', exact: true }).click()
  await expect(drawer.getByRole('button', { name: 'Закрыть меню' })).toBeInViewport()
  expect(await drawer.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.keyboard.press('Escape')
})

test('editorial reveal runs once and reduced motion keeps content visible', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto('/')
  const block = page.locator('[data-reveal]').first()
  await expect(block).toHaveAttribute('data-reveal', 'pending')
  await block.scrollIntoViewIfNeeded()
  await expect(block).toHaveAttribute('data-reveal', 'visible')
  await expect(block).toHaveCSS('opacity', '1')
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await expect(block).toHaveAttribute('data-reveal', 'visible')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  for (const remaining of await page.locator('[data-reveal]').all()) {
    await expect(remaining).toHaveCSS('opacity', '1')
    await expect(remaining).toHaveCSS('transform', 'none')
  }
  await page.getByRole('button', { name: 'Меню', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Навигация' })).toHaveCSS('transition-duration', '0s')
})
